### ISSUE TITLE
Natspec

### ISSUE THREAD

**Issue by pegahcarter** [best-practicers/reviews#59]

**Comment by rihp** [comment]
![Best Practiccers Logo](https://avatars.githubusercontent.com/u/78861553?s=200&v=4)
# _A NATSPEC Review for Kernel's Learning Curve contracts_

> Please bare with me, as this my first time reviewing a contract and I'm very new to solidity. Apologising beforehand in case some of my suggestions are not accurate :)

## [KernelFactory.sol](https://github.com/kernel-community/learning-curve/blob/main/contracts/KernelFactory.sol)

- Interfaces [`I_Vault` and `I_LearningCurve`](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L11-L25) could each use a little one liner description or `@notice` tag maybe?

- Is this [`contract KernelFactory`](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L27-L31) missing the `@params` tag for the structs, or are they correctly documented with inline `//` comments? 
  - Course {checkpoints, fee, checkpointBlockSpacing }
  - Learner {blockRegistered, yieldBatchId, checkpointReached}

 - In these sections, [Lines 37~72](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L37-L72) as well as [Lines 148~158](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L148-L158) the comments are done through several inline and single line annotations, but this commenting style is not used so prominently in other parts of the contract. I'd suggest trying to standardise the commenting style throughout the contracts for better readability. :)

- What are "batches"? After some analysis i'm understanding how it relates to the staking of the DAI in the yearn vaults, but how they're being used is still a bit of an abstract concept.

- The [`verify` function](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L183-L196) has a very long `@notice`. This could be rephrased or split maybe into one `@notice` and one `@dev` tag.  

- Minor detail with [indenting](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L363)  
---

## [LearningCurve.sol](https://github.com/kernel-community/learning-curve/blob/main/contracts/LearningCurve.sol)

- [mint]() : the [GoogleSheets](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/LearningCurve.sol#L50) can be edited by everyone, recommend closing edit permissions to avoid trouble :)

- [doLn](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/LearningCurve.sol#L95-L98): could be good to have a better understanding of why/where this is needed


---

# General recommendations

- I'm very much a newbie when it comes to solidity, so sorry if some of these suggestions are not appropriate!! After a couple of hours of reading through the code its still a bit unclear to me what are all the bits and pieces that conform the system.

- The `@return` tag is only used [once](https://github.com/kernel-community/learning-curve/blob/db117a74b9a24969e852a21257b4442efe13ec16/contracts/KernelFactory.sol#L195), and the `@dev` tag is only used three times ([1](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L345), [2](https://github.com/kernel-community/learning-curve/blob/61fea3584a920b33dab3753dd08cea1872284bdd/contracts/KernelFactory.sol#L363), [3](https://github.com/kernel-community/learning-curve/blob/db117a74b9a24969e852a21257b4442efe13ec16/contracts/LearningCurve.sol#L32)) with very little detail of what those functions are doing. From my perspective of being new to the project, i think a more clear explanation through NATSPEC could help better understand the system. :)

- Documentation with a more detailed description of the end user's flow could be awesome to understand how the value is being moved around. Similarly, could it be possible to see a Threat Model or a Diagram of the system and its components? A quick graph would help a lot to digest and analyse all of its parts. I can help with this in the upcoming days if you guys need :)

> The project looks super cool, and i'd definitely look forward to using this system both as a learner in kernel, and as a teacher for @polywrap and @dOrgTech. Thanks a lot for the opportunity, and hope to continue contributing in the future :D
